### ISSUE TITLE
crashed app

### ISSUE THREAD

**Issue by Srlen** [Whirl21/Select-Menu-Roles#3]
the problem is everytime i npm run test  its says app crashed - waiting for file changes before starting...
![Code_RVInXEZ2cc](https://user-images.githubusercontent.com/87964343/143029614-73f1dd8e-6639-4395-8a37-ec6800a33ca8.jpg)

**Comment by whirlxd** [comment]
as i said remove all the comments from that file

**Comment by Srlen** [comment]
ah i see, btw what command should i use to make select menu?

**Comment by whirlxd** [comment]
you would need to register a slash command called roles
and use it

**Comment by Srlen** [comment]
how to register?

**Comment by whirlxd** [comment]
by learning how to - https://discordjs.guide
